# TCL File Generated by Component Editor 18.1
# Fri Oct 15 10:25:27 CEST 2021
# DO NOT MODIFY


# 
# avalon_pwm "avalon_pwm" v1.0
#  2021.10.15.10:25:27
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_pwm
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_pwm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property ICON_PATH avalon_pwm.vhd
set_module_property DISPLAY_NAME avalon_pwm
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 

# 
# parameters
# 
add_parameter new_parameter INTEGER 0 ""
set_parameter_property new_parameter DEFAULT_VALUE 0
set_parameter_property new_parameter DISPLAY_NAME new_parameter
set_parameter_property new_parameter TYPE INTEGER
set_parameter_property new_parameter UNITS None
set_parameter_property new_parameter ALLOWED_RANGES -2147483648:2147483647
set_parameter_property new_parameter DESCRIPTION ""
set_parameter_property new_parameter AFFECTS_GENERATION false


# 
# display items
# 

