# TCL File Generated by Component Editor 18.1
# Sun Oct 17 20:36:55 CEST 2021
# DO NOT MODIFY


# 
# pwm "pwm" v1.0
#  2021.10.17.20:36:55
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pwm
# 
set_module_property DESCRIPTION ""
set_module_property NAME pwm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME pwm
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pwm_nano
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pwm_nano.vhd VHDL PATH ../pwm_nano/pwm_nano.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1
set_interface_assignment reset New_Key New_Value
set_interface_assignment reset New_Key1 New_Value1


# 
# connection point avalon_slave_pwm
# 
add_interface avalon_slave_pwm conduit end
set_interface_property avalon_slave_pwm associatedClock clock
set_interface_property avalon_slave_pwm associatedReset ""
set_interface_property avalon_slave_pwm ENABLED true
set_interface_property avalon_slave_pwm EXPORT_OF ""
set_interface_property avalon_slave_pwm PORT_NAME_MAP ""
set_interface_property avalon_slave_pwm CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_pwm SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_pwm PWM_OUT readdata Output 1
set_interface_assignment avalon_slave_pwm New_Key New_Value

